# which packages are 'build in to R'
built_in = [
"base",
# "boot", # recommended - but is on cran
"compiler",
"datasets",
"grDevices",
"graphics",
"grid",
"methods",
"parallel",
"R",
"splines",
"stats",
"stats4",
"tcltk",
"tools",
"utils",
# "nlme", - but it is on cran
"BiocInstaller",  # that's the bioconductor install package, which is neither in CRAN, nor in bioconductor's package ilsts

]
