# these get filtered on *output*
# and corretly go down the tree, removing packages that depend on them
# contrast with input_blacklist.txt
# acceptable format is <name>|<name>_<version> or <name>::<date>
# note that that's an underscore!
# to blacklist a package completly, based on it's version, or just on one outpuk date

ROracle = "oracle oci not in nixpkgs, unfree"
Rblpapi = "bloomberg, unfree"

BRugs = "needs OpenBUGS, not in nixpkgs. Or in ubuntu. And the website change log says it hasn't updated since 2014. And the ssl certificate is expired."

Rcplex = "unfree"

bitmexr = "crypto, requires internet to build. "

RQuantLib = "not in nixpkgs"

switchr = "R package managment (not necessary on Nix). Cannot open the connection to 'http://bioconductor.org/config.yaml'"

Rsymphony = "can't find SYMPHONY in nixpkgs"

"baseflow_0.13.2" ="no cargo.lock in download"

elbird = "no libkiwi in nixpkgs, and libwiki compilation needs LFS, and well, that appears broken in fetchgit"

SCATE = "loads SCATEData on build, which fails with experimenthub 'can't fail sensible if offline" # patchme
MAGeCKFlute = "loads demap on build, which needs experimenthub" # patchme
crisprScore = "loads crisprScoreData on build, which needs experimenthub" # patchme

"Rbwa_1.0.0" = "can't find kthread.o. I think kthread.h is missing, and the org github repo is gone"

"SPONGE::2022-04-27" = "object 'combnPrim' is not exported by 'namespace:gRbase'"

"ifultools::2022-04-27" = "error: 'PROBLEM' undeclared (first use in this function)"
"ifultools::2022-05-10" = "error: 'PROBLEM' undeclared (first use in this function)"

"tenXplore::2022-04-27" = """class "RESTfulSummarizedExperiment" is not exported by 'namespace:restfulSE'"""
"tenXplore::2022-05-10" = """class "RESTfulSummarizedExperiment" is not exported by 'namespace:restfulSE'"""


kmcudaR = "cuda not in nixpkgs, removed from cran"
permGPU = "cuda not in nixpkgs, removed from cran"


cplexAPI = "unfree, cplex not in nixpkgs"

"ppmlasso::2021-10-27" = "seems to be incompatible with something: must supply a function skeleton for 'envelope', explicitly or via an existing function"

"signatureSearch::2021-10-26" = 'could not find function "refreshHub'
"signatureSearch::2021-10-27" = 'could not find function "refreshHub'
"affyPara::2021-10-26" = "cannot add binding of '.affyParaInternalEnv' to the base environment"
"ppmlasso::2021-10-26" = "must supply a function skeleton for 'envelope', explicitly or via an existing function"


"sismonr::2021-05-20" = "julia is broken in nixpkgs 20.9"
"IDSpatialStats::2021-05-20" = "Error: object 'bounding.box.xy' is not exported by 'namespace:spatstat'"
"Deducer::2021-05-20" = "Cannot find JRI native library!"
"ppmlasso::2021-05-20" = "must supply a function skeleton for 'envelope', explicitly or via an existing function"
"expp::2021-05-20" = "Error: object 'ripras' is not exported by 'namespace:spatstat'"
"freetypeharfbuzz::2021-05-20" = "configure: error: cannot run C compiled programs. when configuraing patched harfbuzz"
"spANOVA::2021-05-20" = "object 'anova.sarlm' is not exported by 'namespace:spatialreg'"
"rLiDAR::2021-05-20" = "object 'disc' is not exported by 'namespace:spatstat'"
"sbw::2021-05-20" = "object 'disc' is not exported by 'namespace:spatstat'"
"salso::2021-05-20" = "needs rust 1.49, but 1.45.1 is in nixpkgs at this date"
"spsur::2021-05-20" = "namespace 'sparseMVN' 0.2.1 is being loaded, but >= 0.2.1.1 is required"
"vapour::2021-05-20" = "upgrade GDAL to 2.2.2 or later (though we have 2.4.0?..)"
"affyPara::2021-05-20" = "cannot add binding of '.affyParaInternalEnv' to the base environment"
"ChemmineOB::2021-05-20" = "nixpkgs openbabel 2.4.1, but 3.0+ required"

"string2path_0.1.1" = "Cargo.lock references extendr-api github revision that no longer exists"
"sismonr::2021-05-19" = "julia is broken in nixpkgs 20.9"
"IDSpatialStats::2021-05-19" = "Error: object 'bounding.box.xy' is not exported by 'namespace:spatstat'"
"expp::2021-05-19" = "Error: object 'ripras' is not exported by 'namespace:spatstat'"
"freetypeharfbuzz::2021-05-19" = "configure: error: cannot run C compiled programs. when configuraing patched harfbuzz"

"ppmlasso::2021-05-19" = "must supply a function skeleton for 'envelope', explicitly or via an existing function"
"sbw::2021-05-19" = "object 'disc' is not exported by 'namespace:spatstat'"
"vapour::2021-05-19" = "upgrade GDAL to 2.2.2 or later (though we have 2.4.0?..)"
"rLiDAR::2021-05-19" = "object 'disc' is not exported by 'namespace:spatstat'"
"spANOVA::2021-05-19" = "object 'anova.sarlm' is not exported by 'namespace:spatialreg'"
"salso::2021-05-19" = "needs rust 1.49, but 1.45.1 is in nixpkgs at this date"
"spsur::2021-05-19" = "namespace 'sparseMVN' 0.2.1 is being loaded, but >= 0.2.1.1 is required"
"ChemmineOB::2021-05-19" = "nixpkgs openbabel 2.4.1, but 3.0+ required"
"gQTLBase::2021-05-19" = "objects 'clone', 'is.factor.ff' are not exported by 'namespace:ff'"
"Rariant::2021-05-19" = "object 'rbind_all' is not exported by 'namespace:dplyr'"
"Rcwl::2021-05-19" = "no cwltool in nixpks"


"ecospat::2022-11-02" = "namespace 'biomod2' 4.1-2 is being loaded, but < 4.0 is required"
"vapour::2022-11-02" = "'class GDALDataset' has no member named 'SetSpatialRef'"
"delaunay::2022-11-02" = " error: 'itedges' was not declared in this scope; did you mean 'nedges'? "
"GeneTonic::2022-11-02" = "object 'universal' is not exported by 'namespace:backbone'"

"SICtools::2022-11-02"= "Using embedded htslib, error: format not a string literal and no format arguments [-Werror=format-security]"
"Travel::2022-11-02" = "class_Cache_block.h:10:5: error: 'size_t' does not name a type"
"CancerInSilico::2022-11-02"= "Tests/catch.h:6524:45: error: size of array 'altStackMem' is not an integral constant-expression"
"arrow::2022-11-02"= "We need arrow 10.0, but nixpkgs is only up to 9.0.0. Todo"
"PolygonSoup::2022-11-02"= "build failure. Todo"
"happign::2022-11-02"= "build failure, needs internet?. Todo"
"ToxicR::2022-11-02"= "build failure. Todo"

"ArrayExpressHTS::2022-11-02" = "build failure. Todo"
"BioNAR::2022-11-02" = "build failure, todo"
"BitSeq::2022-11-02" = "build failure, todo"
"Rbwa::2022-11-02" = "build failure, todo"
"Rhisat2::2022-11-02" = "build failure, todo"
"signatureSearch::2022-11-02" = "build failure, todo"


"string2path_0.1.3" = "Cargo.lock references extendr-api github revision that no longer exists"
"bivpois_0.50-3.1" = "missing NAMESPACE"

"rshift_2.2.0" = "Missing Cargo.lock"
"hellorust_1.0.1" = "Missing Cargo.lock"
"SpaDES.core::2023-04-26" = "object 'file.move' is not exported by 'namespace:reproducible"
"ino::2023-04-26" = "object 'optimizeR' is not exported by 'namespace:optimizeR'"
"prqlr_0.3.0" = "Cargo.lock references github. Possibly fixable"
"PolygonSoup::2023-04-26"= "build failure. Todo"
"delaunay::2023-04-26"= "build failure. Todo"

"npsp::2023-04-26"= "fortran build issue. Todo"
"longclust::2023-04-26"= "fortran build issue. Todo"
"gps::2023-04-26"= "fortran build issue. Todo"
"EBEN::2023-04-26"= "fortran build issue. Todo"
"bcv::2023-04-26"= "fortran build issue. Todo"
"cgalMeshes::2023-04-26"= "Some kind of boost build issue. Todo"
"IP_0.1" = "can't convince it to find stringprep.ph"
"xtensor_0.14.1-0" = "can't find xtensor-r/rcontainer.hpp." 
"geostatsp_1.8.6" = "geostatsp/libs/geostatsp.so: undefined symbol: GET_SLOT"
"rswipl_9.1.8" = "Cmake can't find ZLIB"
"rhdf5filters_1.12.0" = "can't make it find it's own zstd.h"
"geneSLOPE::2023-04-26" = "object 'create_lambda' is not exported by 'namespace:SLOPE'"
"CaseBasedReasoning_0.1" = "compilation error: mismatched types 'const T2*' and 'int' 75 |   arma::uvec order = arma::sort_index(x, sortDirection) + 1;"
"worldriskpollr_0.7.4" = "downloads from github master upon package load. Reproducibility = no"
"symengine::2023-04-26" = "undefined symbol: basic_abs?"
"OmicsLonDA::2023-04-26" = ": object 'colMeans' is not exported by 'namespace:BiocGenerics'"


"ymd_0.1.0" = "Cargo.lock references extendr-api github: Unsupported crate source 'git+https://github.com/extendr/extendr?rev=refs/pull/627/head#ab1a319e6916995fc10ea3841ecec1ddaf54c9d"
"string2path_0.1.5" = "Cargo.lock references extendr-api github: Unsupported crate source 'git+https://github.com/extendr/extendr?rev=refs/pull/627/head#ab1a319e6916995fc10ea3841ecec1ddaf54c9d"
"rswipl_9.1.17" = "Cmake can't find ZLIB"
"salso::2023-04-27" = "Needs rust 1.65, but 1.64 is in nixpkgs"
"symengine::2023-04-27" = "undefined symbol: basic_abs?"
"dsfa_2.0.0" = "fails to find boost"
"prqlr::2023-04-27" = "Needs rust 1.65, but 1.64 is in nixpkgs"
"RBioFormats_1.0.0" = "Tries to download a jar on load and store in in user cache. Could be patched to actually store it in the build package, I suppose."
"dsfa_2.0.2" = "fails to find boost"
"ragt2ridges::2023-10-24" = "/nix/store/1ajmz5c76f7xi5fanhsfba5srg73hx6f-r-vol2birdR-1.0.1.drv"
"coursekata::2023-10-24" = "Cannot load glue from the private libr"
"tiledb::2023-10-24" = "'TILEDB_BLOB' was not declared in this scope; did you mean 'TILEDB_OR'?"
"BGmix_1.59.0" = "error: reference to 'beta' is ambiguousttps://git.bioconductor.org/packages/BGmix, and deprecated in 3.18"
"Rhdf5lib::2023-10-24" = "We need __func__ or __FUNCTION__ to test function names! compile error"
"OmicsLonDA::2023-10-24" = ": object 'colMeans' is not exported by 'namespace:BiocGenerics'"
"INSPEcT::2023-10-24" = "Error: object 'read.xls' is not exported by 'namespace:gdata"
"BioNAR_1.2.5" = "Tries to talk to experimentHub, can't find the spot"
"multiGSEA_1.10.0" = "Tries to talk to annotationHub, even though metaboliteIDmapping is patched"
"MetaboSignal_1.30.3" = "Tries to talk to annotationHub, even though hpar is patched"
"Rbwa_1.4.0" = "still can't find kthread.o. See 1.0"
"Rarr_1.0.3" = "can't find zlib"
"rshift_3.0.0" = "Missing Cargo.lock"
