# a lookup from the strings that appear in SystemRequirements
# to the actual nix package pkgs.${name}
# you can seperate multiple with spaces.
# teh list get's deduped, so don't worry about pkgconfig repetitions
libcurl = "pkgconfig curl"
"OpenSSL >= 1.0.1" = "pkgconfig openssl openssl.out"
"OpenSSL >= 1.0.2" = "pkgconfig openssl openssl.out"
"OpenSSL" = "pkgconfig openssl openssl.out"
libxml2 = "pkgconfig libxml2"
java = "jdk"
ICU4C = "pkgconfig icu"
PROJ = "pkgconfig proj"
proj = "pkgconfig proj"
"PROJ.4" = "pkgconfig proj"
GDAL = "pkgconfig gdal_2"
GEOS = "pkgconfig geos"
sqlite3 = "pkgconfig sqlite"
gmp = "pkgconfig gmp"
tiff = "pkgconfig libtiff"
libjpeg = "libjpeg"
libpng = "libpng"
# this one needs you to also define an importCargo add_nativeBuildInputs in derivation_args
# todo: automate this...
Cargo = "rustc cargo"
"C++11" = "cmake"
"mono-runtime" = "mono"
"GSL (>= 2.2)" = "pkgconfig gsl"
"GNU Scientific Library" = " pkgconfig gsl_1"
"Gnu Scientific Library" = " pkgconfig gsl_1"
"GNU GSL" = " pkgconfig gsl_1"
"GSL" = " pkgconfig gsl_1"
"gsl" = " pkgconfig gsl_1"
zlib = "zlib"
"fftw (>= 3)"= "pkgconfig fftw"
fftw3 = "pkgconfig fftw"
X11 = "xlibsWrapper"
libavfilter-dev = "ffmpeg"
cairo = "pkgconfig cairo"
libmariadb-client-dev = "pkgconfig libmysqlclient"
#mysql-connector-c = "libmysqlclient"
DieHarder = "dieharder"
ODBC3 = "libiodbc"
netcdf = "netcdf"
udunits = "udunits"
Poppler = "pkgconfig poppler"
libprotobuf = "protobuf"
ProtoBuf = "protobuf"
libjq = "jq"
"ImageMagic++" = "pkgconfig imagemagick"
cmake = "cmake"
"COIN-OR clp" = "pkgconfig clp"
"COIN-OR Clp" = "pkgconfig clp"
GnuPG = "gpgme"
GPGME = "gpgme"
jags = "jags"
JAGS = "jags"
librsvg2 = "pkgconfig librsvg"
GLPK = "pkgconfig glpk"
hiredis = "pkgconfig hiredis"
gmp = "gmp"
mpfr = "mpfr"
FreeType = "freetype"
libssh = "libssh"
"Cyrus SASL" = "cyrus_sasl"
libarchive = "libarchive"
Perl = "perl"
libwebp = "libwebp"
libxslt = "libxslt libxml2"
redland = "pkgconfig redland"
librdf0 = "librdf_raptor2 librdf_rasqal"
libgit2 = "libgit2"

V8 = "v8"
libtiff = "libtiff libdeflate"
OpenCV="pkgconfig opencv"
libsodium="libsodium"
ZeroMQ = "pkgconfig zeromq4"
Scala = "which scala"
"Tcl/TK" = "tk"
fontconfig = "fontconfig"
freetype2 = "freetype"
harfbuzz = "harfbuzz"
fribidi = "fribidi"
